title: blog.Ï€
author: olof

theme: minima
repository: https://github.com/olof/blog
timezone: Europe/Copenhagen

show_excerpts: true

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title
    output: true

exclude:
 - ".gitignore"
